### ISSUE TITLE
Lidar does not work

### ISSUE THREAD

**Issue by Eyos** [mikkleini/rplidar.net#2]
Hi,
I tried to use the provided code and the sample app.
When I click the 'Start' button the lidar rotation stops. When I click the 'Stop' button, the lidar rotation restarts.
I tried different combinations of the options in the drop-down menus, but no scanning.
Am I doing something wrong here? Is there a way to make it work? 

Thanks,
Yossi

Here are log readings from the application:

16:08:10.032 [Demo] Health good. 
16:08:10.302 [Demo] Configuration: 
16:08:10.302 [Demo] 0x0000 - Name: Standard, Ts: 508.00 us, Max distance: 12.00 m, Answer type: 0x81 
16:08:10.302 [Demo] 0x0001 - Name: Express, Ts: 254.00 us, Max distance: 12.00 m, Answer type: 0x82 
16:08:10.302 [Demo] 0x0002 - Name: Boost, Ts: 127.00 us, Max distance: 12.00 m, Answer type: 0x84 
16:08:10.302 [Demo] 0x0003 - Name: Sensitivity, Ts: 127.00 us, Max distance: 12.00 m, Answer type: 0x84 (typical) 
16:08:10.302 [Demo] 0x0004 - Name: Stability, Ts: 201.00 us, Max distance: 12.00 m, Answer type: 0x84 
16:08:10.302 [Demo] Scanning started. 
16:08:13.343 [Lidar] Timeout at receiving data for legacy scan. 
16:08:17.038 [Lidar] Timeout at receiving descriptor for get health. 
16:08:18.054 [Demo] Health good. 
16:08:18.116 [Demo] Configuration: 
16:08:18.116 [Demo] 0x0000 - Name: Standard, Ts: 508.00 us, Max distance: 12.00 m, Answer type: 0x81 
16:08:18.116 [Demo] 0x0001 - Name: Express, Ts: 254.00 us, Max distance: 12.00 m, Answer type: 0x82 
16:08:18.116 [Demo] 0x0002 - Name: Boost, Ts: 127.00 us, Max distance: 12.00 m, Answer type: 0x84 
16:08:18.116 [Demo] 0x0003 - Name: Sensitivity, Ts: 127.00 us, Max distance: 12.00 m, Answer type: 0x84 (typical) 
16:08:18.116 [Demo] 0x0004 - Name: Stability, Ts: 201.00 us, Max distance: 12.00 m, Answer type: 0x84 
16:08:18.132 [Demo] Scanning started. 
16:08:21.152 [Lidar] Timeout at receiving data for legacy scan.

**Comment by Robakuuu** [comment]
Same problem here :/

**Comment by mikkleini** [comment]
The problem was in inversion of DTC signal in ControlMotorDtr. For the lidar I used with USB-UART converter, I had to invert it. I took that inversion out.

**Comment by Eyos** [comment]
It works great now, thanks a lot!
Is there a way to stop the motor and start it when needed?

**Comment by mikkleini** [comment]
> Is there a way to stop the motor and start it when needed?

Yes, with ControlMotorDtr function.

**Comment by Eyos** [comment]
Thanks!
